# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: one
  value: initialValue
- name: environ
  value: "It's a dev environ"

stages:
- stage:
  jobs:
  - job:
    steps:
    - script: echo my stuff is $(one) amnd $(environ)