# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# normally, you can 
# trigger:
# - main

pr: none
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - demos/ReimbursementApi


pool:
  vmImage: ubuntu-latest


jobs:
- job: job1
  steps:
  - script: echo Hello, world!
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo My name is Earl!
    displayName: 'Run a multi-line script'
- job: job2
  dependsOn: job1
  steps:
  - script: echo This is job2
    displayName: 'Run a one-line script'
  - script: |
      echo Add other tasks to build, test, and deploy your project.
    displayName: 'Run a multi-line script'
