

--GamePieces
CREATE TABLE GamePieces(
GamePieceId INT PRIMARY KEY IDENTITY(0,1),
GamePieceNumber INT NOT NULL DEFAULT -1,
Name nvarchar(20) NOT NULL
);

--player
CREATE TABLE Players(
PlayerId UNIQUEIDENTIFIER PRIMARY KEY,
Fname VARCHAR(30) NOT NULL DEFAULT 'default_Firstname',
Lname VARCHAR(30) NOT NULL DEFAULT 'default_Lastname',
Wins INT NOT NULL DEFAULT 0,
Losses INT NOT NULL DEFAULT 0,
);

--Game
CREATE TABLE Games(
GameId UNIQUEIDENTIFIER PRIMARY KEY,
GameDate Date DEFAULT GETDATE(),
NumTies INT NOT NULL DEFAULT 0,-- could add a check to always be positive.
P1 UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
P2 UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
GameWinner_PlayerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
);

--round
CREATE TABLE Rounds(
RoundId UNIQUEIDENTIFIER PRIMARY KEY,
P1Choice INT NOT NULL FOREIGN KEY REFERENCES GamePieces(GamePieceId),
P2Choice INT NOT NULL FOREIGN KEY REFERENCES GamePieces(GamePieceId),
GameId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Games(GameId),
RoundWinner_PlayerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
);



-- Player_GameJunction
CREATE TABLE Player_Game_Junction(
P1_PlayerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
P2_PlayerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId),
GameId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Players(PlayerId)
);
